### PR TITLE
Practical exam..moved files in resp directories

### PR DESCRIPTION
**Pull request by shruti1099**

### CODE REVIEW

**Comment by abhishek30221** [comment]
Q1 and Q2 were directories not files

**Comment by shruti1099** [comment]
I didn't understand. What to do now?

**Comment by abhishek30221** [comment]
Capture
see Shruti , 
here you have your ClassrollNo_UnivrollNo_Name directory
After that there is q1.html
This q1.html should be inside Q1 directory
and same goes for Q2

SUMMARY: you need to make Q1 and Q2 seperate directories inside your main folder.
inside them you have to put your Q1 solution files. ( same goes for Q2)

**Comment by shruti1099** [comment]
Yes now I got it.. thankyou

**Comment by shruti1099** [comment]
Hi..I have made the required changes now. Created directories of q1 and q2.

**Pull request merged**
